language: node_js
node_js:
  - lts/*
install:
  - npm ci

deploy:
  provider: npm
  email: mengfei0053@live.com
  api_key: $NPM_TOKEN 

script:
  - npm run test
  - echo $NPM_TOKEN
  - npm --version
  - node --version
  - npm publish 

branches:
  only:
    - release